name: Run Python Script

on:
  push:          # 每次 push 时触发
    branches:
      - main     # 仅当 push 到 main 分支时触发
  schedule:
    # 每天 UTC 时间 0 点运行一次 (cron 语法)
    - cron: "0 0 * * *"
  workflow_dispatch:  # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认 GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # 你需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cp python/page_parser.py $(dirname $(which python))/../lib/*/*/weibo_spider/parser/page_parser.py
          cp python/util.py $(dirname $(which python))/../lib/*/*/weibo_spider/parser/util.py

      - name: Run script
        run: |
          cd python/config
          python -m weibo_spider --output_dir="./weibo"
          ls -R
          cd ..
          echo $PWD
          python main.py

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add database/
          git add python/config/user_id_list.txt
          git commit -m "Update database from workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/renlililoli/IdolPosts.git HEAD:main

      - name: Render JSONL to HTML
        run: |
          python python/render_jsonl_to_html.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          persist-credentials: false  # 禁用默认 GITHUB_TOKEN
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: IdolPosts
          to: ${{ secrets.SMTP_USER }}
          from: ${{ secrets.SMTP_USER }}
          body: "请查看附件: database/result.html"
          attachments: database/result.html
          secure: true


