name: Run Python Script

on:
  push:          # 每次 push 时触发
    branches:
      - main     # 仅当 push 到 main 分支时触发
  schedule:
    # 每天 UTC 时间 0 点运行一次 (cron 语法)
    - cron: "0 0 * * *"
  workflow_dispatch:  # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # 你需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果有依赖

      - name: Run script
        run: |
          echo $PWD
          cd python/config
          echo $PWD
          python -m weibo_spider --output_dir="./weibo"
          ls -R
          cd ..
          echo $PWD
          python main.py
